version: '3'

services:
  postgres:
    container_name: contenedor_postgres
    image: postgres
    restart: always
    volumes:
      - postgres2:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - red_postgres

  pgadmin:
    container_name: contenedor_pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
    ports:
      - "2345:80"
    networks:
      - red_postgres

  ubuntuhack:
    container_name: ubuntu_hack
    image: ubuntu
    networks:
      - red_postgres
    volumes:
      - nuevovol:/home
    restart: always
    command: ["sleep","infinity"]


volumes:
  nuevovol:
  postgres2:

networks:
  red_postgres:
    driver: bridge
